"""v4

Revision ID: 6a645bbf9b24
Revises: c5957bfcbdf4
Create Date: 2024-09-02 19:49:35.755148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a645bbf9b24'
down_revision: Union[str, None] = 'c5957bfcbdf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cve_record', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cve_record_data', 'date_published',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cve_record_data', 'date_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cve_record_data', 'descriptions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cve_record_data', 'descriptions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cve_record_data', 'date_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cve_record_data', 'date_published',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cve_record', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
