"""v5

Revision ID: bf26d2b7a9d3
Revises: 6a645bbf9b24
Create Date: 2024-09-03 01:08:38.620108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf26d2b7a9d3'
down_revision: Union[str, None] = '6a645bbf9b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_record',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'cve_record_data', 'cve_record', ['cve_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cve_record_data', type_='foreignkey')
    op.drop_table('cve_record')
    # ### end Alembic commands ###
